nextflow run trios.nf \
        -profile docker \
        -resume \
        --mode "all" \
	    --remap true \
	    --bwa 2 \
 	    --runID "bwa2" \
	    --exome true \
	    --samplesheet "/home/mateuszsypniewski/cholestaza/manifest_bam.csv" \
        --ped "/home/mateuszsypniewski/cholestaza/samples.ped" \
	    --outfolder "/data/output/cholestaza" \
	    --fasta "/data/references/fasta/GRCh38/GRCh38.fa" \
	    --snv_resource "/data/references/germline_resource/gnomAD4/gnomad_snv_v4.0_complete.vcf.gz" \
	    --contigs_bed "/data/references/bed/GRCh38/hg38_Twist_ILMN_Exome_2.0_Plus_Panel_Combined_Mito.bed.gz" \
	    --exclude_bed "/data/references/bed/GRCh38/exclude.cnvnator_100bp.GRCh38.20170403.bed" \
        --delly_map "/data/references/delly/Homo_sapiens.GRCh38.dna.primary_assembly.fa.r101.s501.blacklist.gz" \
        --vep_cache "/data/references/vep" \
        --clinvar "/data/references/clinvar/GRCh38/clinvar_20240520.vcf.gz" \
        --REVEL "/data/references/germline_resource/REVEL/new_tabbed_revel_grch38.tsv.gz" \
        --genome "GRCh38"